package Grpc::XS::Constants;

use strict;
use warnings;

use Grpc::XS;
use base qw(Exporter);

our @EXPORT_OK = qw(
  GRPC_CALL_OK
  GRPC_CALL_ERROR
  GRPC_CALL_ERROR_NOT_ON_SERVER
  GRPC_CALL_ERROR_NOT_ON_CLIENT
  GRPC_CALL_ERROR_ALREADY_INVOKED
  GRPC_CALL_ERROR_NOT_INVOKED
  GRPC_CALL_ERROR_ALREADY_FINISHED
  GRPC_CALL_ERROR_TOO_MANY_OPERATIONS
  GRPC_CALL_ERROR_INVALID_FLAGS
  GRPC_WRITE_BUFFER_HINT
  GRPC_WRITE_NO_COMPRESS
  GRPC_STATUS_OK
  GRPC_STATUS_CANCELLED
  GRPC_STATUS_UNKNOWN
  GRPC_STATUS_INVALID_ARGUMENT
  GRPC_STATUS_DEADLINE_EXCEEDED
  GRPC_STATUS_NOT_FOUND
  GRPC_STATUS_ALREADY_EXISTS
  GRPC_STATUS_PERMISSION_DENIED
  GRPC_STATUS_UNAUTHENTICATED
  GRPC_STATUS_RESOURCE_EXHAUSTED
  GRPC_STATUS_FAILED_PRECONDITION
  GRPC_STATUS_ABORTED
  GRPC_STATUS_OUT_OF_RANGE
  GRPC_STATUS_UNIMPLEMENTED
  GRPC_STATUS_INTERNAL
  GRPC_STATUS_UNAVAILABLE
  GRPC_STATUS_DATA_LOSS
  GRPC_OP_SEND_INITIAL_METADATA
  GRPC_OP_SEND_MESSAGE
  GRPC_OP_SEND_CLOSE_FROM_CLIENT
  GRPC_OP_SEND_STATUS_FROM_SERVER
  GRPC_OP_RECV_INITIAL_METADATA
  GRPC_OP_RECV_MESSAGE
  GRPC_OP_RECV_STATUS_ON_CLIENT
  GRPC_OP_RECV_CLOSE_ON_SERVER
  GRPC_CHANNEL_IDLE
  GRPC_CHANNEL_CONNECTING
  GRPC_CHANNEL_READY
  GRPC_CHANNEL_TRANSIENT_FAILURE
  GRPC_CHANNEL_FATAL_FAILURE
  GPR_CLOCK_MONOTONIC
  GPR_CLOCK_REALTIME
  GPR_CLOCK_PRECISE
  GPR_TIMESPAN
);

1;
